### ISSUE TITLE
支持react native、ssr吗

### ISSUE THREAD

**Issue by hu-tu-yi-shi** [nanxiaobei/resso#10]

**Comment by nanxiaobei** [comment]
目前因为引入了 `react-dom` 的 API，暂不支持 react native，后面可能会更新。
SSR 未测试过，但应该没有问题。

**Comment by nanxiaobei** [comment]
`0.6.0` 已更新，移除了 `react-dom` 引入，现可用于 React Native 与 SSR。

**Comment by hu-tu-yi-shi** [comment]
完善下readme吧     让大家都可以快速知道  支持  React Native 与 SSR。
