### ISSUE TITLE
求教：如何写计算属性呢

### ISSUE THREAD

**Issue by nilzhao** [nanxiaobei/resso#11]
```js
const store = resso({
  count: 0,
  get double() {
    return this.count * 2;
  },
});
```
我是这么写的，但是 double 不会更新
https://codesandbox.io/s/headless-wind-u6v73m?file=/src/App.js

**Comment by awttt** [comment]
> ```js
> const store = resso({
>   count: 0,
>   get double() {
>     return this.count * 2;
>   },
> });
> ```
> 
> 我是这么写的，但是 double 不会更新 https://codesandbox.io/s/headless-wind-u6v73m?file=/src/App.js



> 

我发现在APP里只有把count引入才会更新
//App.jsx
const { count,double } = counterStore;

**Comment by awttt** [comment]
> ```js
> const store = resso({
>   count: 0,
>   get double() {
>     return this.count * 2;
>   },
> });
> ```
> 
> 我是这么写的，但是 double 不会更新 https://codesandbox.io/s/headless-wind-u6v73m?file=/src/App.js



> 

我发现在APP里只有把count引入才会更新
//App.jsx
const { count,double } = counterStore;

**Comment by nanxiaobei** [comment]
目前不支持计算属性。

"引入" 相当于 `useState`（注册 `count` state），若不引入 `count`，则对 `count` 赋值不触发此处 UI 更新。

计算属性目前没想到比较好的 API 设计方式，也不会推荐使用 `this`，但似乎确实可以通过此 hack 方式实现计算属性。

**Comment by fantasticsoul** [comment]
试试响应式的原子化状态引擎helux https://github.com/heluxjs/helux , 你想要的都有
