### ISSUE TITLE
Nested objects?

### ISSUE THREAD

**Issue by lgabv** [nanxiaobei/resso#13]
Hey,

First of all great job :)

just have a question about nested object like this one:

```
const store = resso({
  user: {
    info: {
      count: 0,
    }
  },
  inc: () => store.user.info.count++,
});

function Control() {
  const { inc } = store;
  return (
    <>
      <p>{store.user.info.count}</p>
      <button onClick={inc}>-</button>
    </>
  );
}
```

Maybe this line https://github.com/nanxiaobei/resso/blob/main/src/index.ts#L31 should be some recursive function?
I'm not so good so ... I don't have any PR or suggestions ... just try to learn :) Thanks in advance!

**Comment by nanxiaobei** [comment]
Not support nested object, can see this article https://nanxiaobei.medium.com/resso-worlds-simplest-react-state-manager-a3b1b0ccaa99 (search "Set store")

**Comment by fantasticsoul** [comment]
If you want to enjoy nested object feature, you can try reactive atomic state engine helux: https://github.com/heluxjs/helux
