### ISSUE TITLE
hook数量不一致疑问

### ISSUE THREAD

**Issue by jackeryjam** [nanxiaobei/resso#14]
大佬这个库确实大道至简，非常棒！
但是这个用provy代理get，实际上是执行一个hook，开发者不会把它当成是hook去注意，可能会不经意间放到条件语句里面，导致错误
<img width="675" alt="image" src="https://user-images.githubusercontent.com/32444505/204122623-3896a3ce-8b5f-4392-b62a-74f9bef460b4.png">
就像这种情况，感觉有点美中不足😂

**Comment by nanxiaobei** [comment]
是这样的，但也只能在 README 里提醒了 ... 
https://github.com/nanxiaobei/resso/blob/main/README.zh-CN.md#api
