### ISSUE TITLE
目前不支持订阅更新吗？是否有计划？

### ISSUE THREAD

**Issue by xgfone** [nanxiaobei/resso#16]

**Comment by nanxiaobei** [comment]
类似 `watch` 的功能，目前暂无计划添加

**Comment by fantasticsoul** [comment]
可以试试响应式原子化状态引擎 helux https://github.com/heluxjs/helux，你所有想要的功能都有哦，还能更多你想不到的

**Comment by bosens-China** [comment]
@nanxiaobei 如果跟本地储存联动，我想持久化数据
