### ISSUE TITLE
多实例场景

### ISSUE THREAD

**Issue by weihomechen** [nanxiaobei/resso#21]
hi, 遇到个问题请教下，可能是我的场景有问题，求解惑

组件多次实例化后，store也只有一个，期望组件在外部被使用时，store是独立的且不相互影响

尤其在npm包内，是当做全局状态使用的，但是发包后被多次import后，每个组件操作的是同一个store

https://codesandbox.io/p/sandbox/winter-flower-npgqwy?file=%2Fsrc%2Findex.tsx%3A23%2C40

**Comment by nanxiaobei** [comment]
是的，操作的是同一个 store，目前暂不支持多实例的场景。

**Comment by weihomechen** [comment]
> 是的，操作的是同一个 store，目前暂不支持多实例的场景。

大佬，可以问一下有支持的计划么，请教下是否有解决思路~~我这边用在npm包内，发包后页面上存在多个实例，操作的同一个store对象，thx~

**Comment by nanxiaobei** [comment]
短期内应该不会，后面有需求较多的话可能会考虑。
