### ISSUE TITLE
功能需求，建议添加一个 reset 方法

### ISSUE THREAD

**Issue by defolly** [nanxiaobei/resso#22]
pinia 的 $reset 方法很好用的， 建议添加 reset 方法， 所有值返回到初始状态。

使用场景：
某些模块功能比较复杂，使用了 独立的 store, 所有子组件共享状态，当用户切换到其它模块后再次切换回来时，希望状态值回到初始化值。目前通过定义 store的时候，再写一个initStore来处理，实现起来比较繁琐，如果内部能实现就更好了。
<img width="391" alt="image" src="https://github.com/nanxiaobei/resso/assets/10161473/69493b62-ece4-4c02-adcb-0263babc2fa0">

**Comment by nanxiaobei** [comment]
可以这么写：

```js
const intialState = { a: 1, b: 2 }

const store = resso({
  ...JSON.parse(JSON.stringify(intialState)),

  reset() {
    store(JSON.parse(JSON.stringify(intialState)))
  }
})

store.reset()
```
