### ISSUE TITLE
感觉思路豁然开朗，想生产环境使用，不知道可行吗。

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [nanxiaobei/resso#3]
真的是状态管理就只要做好状态管理的事情。。瞬间感觉recoil就不香了

**Comment by liuhuapiaoyuan** [comment]
有没有考虑过插件，中间件机制，比较好处理一下异步逻辑

**Comment by nanxiaobei** [comment]
感谢~
1. 生产环境理论上是可行的，代码量很少，有问题也不会是黑盒，很容易看懂并解决
2. 插件机制暂未考虑添加
3. 异步函数直接定义并使用就好，没有与 Redux 一样的 "异步" 问题（其实 Redux 的异步问题是它希望 dispatch(asyncFn)，而默认只能 dispatch(actionObj)，看下 redux-thunk 的代码，不到 10 行，看完会崩溃）

**Comment by liuhuapiaoyuan** [comment]
> 

嗯 ，我看过他源码，仅仅是判断是否是async|Promise，如果是的话注入dispath，将异步问题回调化。
我就是希望有插件机制，依次解决大量的loading，error等问题。
我现在是基于context写了一个useController，依次将resso和ahooks/useRequest进行结合，但是总感觉有点别扭。
因为项目时间有限，也就先这样顶上去了，但是我总觉得应该在resson中有机会去扩展loading|error等

**Comment by nanxiaobei** [comment]
`useRequest` 与 `swr` 是将 request 与 state 结合在了一起，所以会有 loading error 等。
`resso` 目前还是专用于 state 共享，不涉及 request 这一块。
未来可能会添加 async function 的 loading state，这样可以将请求定义在 store 在。

**Comment by fwtcumt** [comment]
> `useRequest` 与 `swr` 是将 request 与 state 结合在了一起，所以会有 loading error 等。 `resso` 目前还是专用于 state 共享，不涉及 request 这一块。 未来可能会添加 async function 的 loading state，这样可以将请求定义在 store 内。

还是希望始终坚持成为一个高效、单纯的状态管理工具，能保存数据、更新数据、数据变更后能高效通知界面更新，足矣。至于数据如何使用，需要兼容罕见复杂场景，不是你这个工具的任务。
