### ISSUE TITLE
支持批量更新吗？如果不支持将来考虑支持吗？

### ISSUE THREAD

**Issue by Bubbleinpit** [nanxiaobei/resso#4]
类似于 mobx 中将多个修改操作放在 runInAction() 中执行，来批量更新 state 之后再触发 rerender。

**Comment by nanxiaobei** [comment]
目前就是批量更新，会检测 `react-dom` 的 `unstable_batchedUpdates`。

**Comment by huyansheng3** [comment]
和mobx的批量更新不太一样。 实际render函数会执行多次，如果中间状态不符合预期，会导致中间可能会渲染出错
