### ISSUE TITLE
Why must destructure first?

### ISSUE THREAD

**Issue by weigaosS** [nanxiaobei/resso#5]
Where is the code design that must be deconstructed before use ？

**Comment by nanxiaobei** [comment]
Store data will be inject into a component using `useState`, destructure is calling `useState`.

So need to follow the Hooks rules, at the top level of a component, cannot after `if`, and then use, otherwise there will be a React warning.

**Comment by oleggrishechkin** [comment]
@nanxiaobei Maybe you can create a hook like `const { prop } = useResso(state)` - linter will work correctly with hook rules and state destruction will be more transparent

`useResso` is just a `(state) => state`

**Comment by nanxiaobei** [comment]
here is an introduction about the API design thinking:

https://nanxiaobei.medium.com/resso-worlds-simplest-react-state-manager-a3b1b0ccaa99

You can check "5. How the API of resso is designed?" part~

**Comment by oleggrishechkin** [comment]
Yes, I'm understand that it's a featue) And I think it look good.
